AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  smart-door-serverless

  Sample SAM Template for smart-door-serverless

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
# Globals:
#   Function:
#     Timeout: 3

Resources:
  SDLF0Function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./SDLF0/
      Handler: app.lambda_handler
      Runtime: python3.7
      Timeout: 200
      Events:
        SDLF0:
          Type: Api 
          Properties:
            Path: /SDLF0
            Method: get

  SDLF1Function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./SDLF1/
      Handler: app.lambda_handler
      Runtime: python3.7
      Timeout: 200
      Events:
        SDLF0:
          Type: Api 
          Properties:
            Path: /SDLF1
            Method: get

  SDLF2Function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./SDLF2/
      Handler: app.lambda_handler
      Runtime: python3.7
      Timeout: 200
      Events:
        SDLF0:
          Type: Api 
          Properties:
            Path: /SDLF2
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  SDLF0WorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  SDLF0Function:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt SDLF0Function.Arn
  SDLF0FunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt SDLF0FunctionRole.Arn
